export const Playlist = [
  {
    id: 1,
    title: 'The First Song',
    artist: 'Artist 1',
    curator: 'Curator 1',
    artCover: '/images/1.jpg',
    duration: '04:20',
  },
  {
    id: 2,
    title: 'The Second Song',
    artist: 'Artist 2',
    curator: 'Curator 2',
    artCover: '/images/2.jpg',
    duration: '02:20',
  },
  {
    id: 3,
    title: 'The Third Song',
    artist: 'Artist 3',
    curator: 'Curator 3',
    artCover: '/images/3.jpg',
    duration: '03:20',
  },
  {
    id: 4,
    title: 'The Fourth Song',
    artist: 'Artist 4',
    curator: 'Curator 4',
    artCover: '/images/4.jpg',
    duration: '01:40',
  },
  {
    id: 5,
    title: 'The Fifth Song',
    artist: 'Artist 5',
    curator: 'Curator 5',
    artCover: '/images/5.jpg',
    duration: '02:40',
  },
  {
    id: 6,
    title: 'The Sixth Song',
    artist: 'Artist 6',
    curator: 'Curator 6',
    artCover: '/images/6.jpg',
    duration: '03:16',
  },
  {
    id: 7,
    title: 'The Seventh Song',
    artist: 'Artist 7',
    curator: 'Curator 7',
    artCover: '/images/7.jpg',
    duration: '02:34',
  },
  {
    id: 8,
    title: 'The Eighth Song',
    artist: 'Artist 8',
    curator: 'Curator 8',
    artCover: '/images/8.jpg',
    duration: '03:45',
  },
  {
    id: 9,
    title: 'The Ninth Song',
    artist: 'Artist 9',
    curator: 'Curator 9',
    artCover: '/images/9.jpg',
    duration: '02:47',
  },
  {
    id: 10,
    title: 'The Tenth Song',
    artist: 'Artist 10',
    curator: 'Curator 10',
    artCover: '/images/10.jpg',
    duration: '03:03',
  },
  {
    id: 11,
    title: 'The Eleventh Song',
    artist: 'Artist 11',
    curator: 'Curator 11',
    artCover: '/images/11.jpg',
    duration: '02:03',
  },
  {
    id: 12,
    title: 'The Twelfth Song',
    artist: 'Artist 12',
    curator: 'Curator 12',
    artCover: '/images/12.jpg',
    duration: '03:53',
  },
]
