import type { NextPage } from 'next'
import Head from 'next/head'
import { UpdateTitle, UpdateTokenPass } from '@public-assembly/assemble-curation-functions'

const Home: NextPage = () => {
  
  return (
    <div>
      <Head>
        {/*
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        */}
      </Head>
      <UpdateTitle curationContract={'0x34fe32e6442d14d923953a537b8163365630b5a7'} title={'secondTitle'} />
    </div>
  )
}

export default Home
