import type { NextPage } from 'next'
import Head from 'next/head'
import { useOwnerCurationFunctions } from '@public-assembly/assemble-curation-functions'
import { useState } from 'react'

const Home: NextPage = () => {
  // Set curation contract address as an environment variable
  const curationContract = process.env.NEXT_CURATION_CONTRACT_ADDRESS as string

  // Add a useState hook to handle the relevant input
  const [title, setTitle] = useState('')
  const [tokenPass, setTokenPass] = useState('')

  // Destructure the functions you want to invoke from the useOwnerCurationFunctions hook and pass in the appropriate props
  const { updateTitleWrite, updateTokenPassWrite } = useOwnerCurationFunctions({
    curationContract,
    title,
    tokenPass,
  })

  return (
    <div>
      <Head>
        {/*
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        */}
      </Head>

      <div className="mx-auto max-w-sm">
        <div className="flex flex-wrap">
          <label className="block my-4">
            <span className="text-gray-700">Update Title</span>
            <input
              className="p-2 mt-2 block w-full rounded-md bg-slate-200"
              onChange={(e) => setTitle(e.target.value)}
            />
            <button
              className="bg-blue-500 w-48 text-center p-2 mt-4 rounded-md text-white hover:bg-blue-600"
              onClick={() => updateTitleWrite?.()}>
              Update Title
            </button>
          </label>
          <label className="block my-4">
            <span className="text-gray-700">Update Title</span>
            <input
              className="p-2 mt-2 block w-full rounded-md bg-slate-200"
              onChange={(e) => setTokenPass(e.target.value)}
            />
            <button
              className="bg-blue-500 w-48 text-center p-2 mt-4 rounded-md text-white hover:bg-blue-600"
              onClick={() => updateTokenPassWrite?.()}>
              Update Token Pass
            </button>
          </label>
        </div>
      </div>
    </div>
  )
}

export default Home
